import fs from 'fs'
import path from 'path'
import { chat } from '../ollama/OllamaClient.js'
import { loadConfig } from '../ollama/ModelManager.js'
import { updateSessionSummary } from '../persistence/SessionStore.js'

const IGNORE = new Set([
  '.git', 'node_modules', 'dist', 'build', '.next', 'target',
  '.localforge', '__pycache__', '.venv', 'venv', '.DS_Store',
  'coverage', '.turbo', '.vercel',
])

const KEY_FILES = [
  'package.json', 'README.md', 'readme.md', 'README.txt',
  'pyproject.toml', 'Cargo.toml', 'go.mod', 'pom.xml',
  'tsconfig.json', 'vite.config.ts', 'next.config.js',
  '.env.example', 'docker-compose.yml', 'Dockerfile',
  'main.ts', 'main.tsx', 'index.ts', 'index.tsx', 'app.ts', 'app.tsx',
  'main.py', 'app.py', 'main.go', 'main.rs',
]

export interface ProjectScan {
  fileTree:    string        // ASCII tree
  fileList:    string[]      // flat list of all file paths
  keyContents: Record<string, string>  // filename -> content (trimmed)
  isEmpty:     boolean
  summary?:    string        // generated by model
}

export function scanProjectFiles(rootPath: string): ProjectScan {
  if (!fs.existsSync(rootPath)) {
    return { fileTree: '', fileList: [], keyContents: {}, isEmpty: true }
  }

  const fileList: string[] = []
  const keyContents: Record<string, string> = {}
  const treeLines: string[] = [path.basename(rootPath) + '/']

  function walk(dir: string, depth: number, prefix: string) {
    if (depth > 5) return
    let entries: fs.Dirent[]
    try { entries = fs.readdirSync(dir, { withFileTypes: true }) } catch { return }

    const filtered = entries.filter(e => !IGNORE.has(e.name))
    filtered.forEach((entry, i) => {
      const isLast      = i === filtered.length - 1
      const connector   = isLast ? '└── ' : '├── '
      const childPrefix = isLast ? '    ' : '│   '
      const fullPath    = path.join(dir, entry.name)

      treeLines.push(`${prefix}${connector}${entry.name}${entry.isDirectory() ? '/' : ''}`)

      if (entry.isDirectory()) {
        walk(fullPath, depth + 1, prefix + childPrefix)
      } else {
        fileList.push(fullPath)
        if (KEY_FILES.includes(entry.name)) {
          try {
            const content = fs.readFileSync(fullPath, 'utf8')
            // Trim to 2000 chars so we don't overflow context
            keyContents[entry.name] = content.slice(0, 2000)
          } catch { }
        }
      }
    })
  }

  walk(rootPath, 1, '')

  return {
    fileTree:    treeLines.join('\n'),
    fileList,
    keyContents,
    isEmpty:     fileList.length === 0,
  }
}

export async function generateProjectSummary(
  sessionId: string,
  rootPath:  string,
  scan:      ProjectScan
): Promise<string> {
  if (scan.isEmpty) {
    const summary = 'Empty project — no files yet.'
    updateSessionSummary(sessionId, summary)
    return summary
  }

  const { selectedModel } = loadConfig()

  const keyFilesBlock = Object.entries(scan.keyContents)
    .map(([name, content]) => `=== ${name} ===\n${content}`)
    .join('\n\n')

  const prompt = `You are analysing a software project. Based on the file tree and key file contents below, write a concise technical summary (max 200 words) covering:
- What the project is and its purpose
- The tech stack and main frameworks
- The current state (empty / early / in-progress / complete)
- Key directories and what they contain

File tree:
${scan.fileTree}

Key file contents:
${keyFilesBlock || 'No key files found.'}

Write only the summary, no preamble.`

  try {
    const summary = await chat(selectedModel, [
      { role: 'system', content: 'You are a precise technical analyst. Write concise, factual project summaries.' },
      { role: 'user',   content: prompt }
    ])
    updateSessionSummary(sessionId, summary)
    return summary
  } catch (err) {
    const fallback = `Project at ${rootPath} — ${scan.fileList.length} files found. Auto-summary unavailable.`
    updateSessionSummary(sessionId, fallback)
    return fallback
  }
}
